version: 0.0
os: linux	
files:	
  - source: /index.html	  
    destination: /var/www/html/	    
hooks:	
  BeforeInstall:	 
    - location: scripts/install_dependencies	   
      timeout: 600	     
      runas: root	     
    - location: scripts/start_server	    
      timeout: 300	     
      runas: root	      
